name: Zip Example Cases

on: [push, pull_request]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: examples/
          dest: examples.zip